definitions:
  model.ListData:
    properties:
      count:
        type: integer
      list:
        type: object
    type: object
  util.ApiResp:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
      status:
        type: boolean
    type: object
info:
  contact: {}
  license: {}
paths:
  /admin/article:
    delete:
      consumes:
      - application/x-www-form-urlencoded
      description: 删除文章。和分类的关系是一个分类对应多个文章，和标签的关系是多对多。
      parameters:
      - description: 文章id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ApiResp'
        "302":
          description: Found
          schema:
            $ref: '#/definitions/util.ApiResp'
      summary: 文章删除
      tags:
      - 文章管理
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: 文章列表。和分类的关系是一个分类对应多个文章，和标签的关系是多对多。
      parameters:
      - description: 页码
        in: path
        name: page
        type: integer
      - description: 每页显示条数
        in: path
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ApiResp'
        "302":
          description: Found
          schema:
            $ref: '#/definitions/util.ApiResp'
      summary: 文章列表
      tags:
      - 文章管理
    post:
      consumes:
      - application/json
      description: 编辑文章和分类的关系是一个分类对应多个文章，和标签的关系是多对多。注：请求格式为json
      parameters:
      - description: 文章id
        in: body
        name: id
        required: true
        schema:
          type: integer
      - description: 分类id
        in: body
        name: cid
        required: true
        schema:
          type: integer
      - description: 标签id
        in: body
        name: tag_id
        schema:
          type: integer
      - description: 标题
        in: body
        name: title
        required: true
        schema:
          type: string
      - description: 描述
        in: body
        name: description
        required: true
        schema:
          type: string
      - description: 内容
        in: body
        name: body
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ApiResp'
        "302":
          description: Found
          schema:
            $ref: '#/definitions/util.ApiResp'
      summary: 文章更新
      tags:
      - 文章管理
  /admin/article/:id:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: 获取文章详情。和分类的关系是一个分类对应多个文章，和标签的关系是多对多。
      parameters:
      - description: 文章id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ApiResp'
        "302":
          description: Found
          schema:
            $ref: '#/definitions/util.ApiResp'
      summary: 文章详情
      tags:
      - 文章管理
  /admin/article_order/:id:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: 修改文章排序。
      parameters:
      - description: 文章id
        in: path
        name: id
        required: true
        type: integer
      - description: 顺序，数值越大越靠前
        in: formData
        name: order
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ApiResp'
        "302":
          description: Found
          schema:
            $ref: '#/definitions/util.ApiResp'
      summary: 文章排序
      tags:
      - 文章管理
  /admin/article_tag/:id:
    put:
      consumes:
      - application/json
      description: 给文章快速设置标签，请设置请求格式为json
      parameters:
      - description: 文章id
        in: path
        name: id
        required: true
        type: integer
      - description: 标签id列表
        in: body
        name: tag_id
        required: true
        schema:
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ApiResp'
        "302":
          description: Found
          schema:
            $ref: '#/definitions/util.ApiResp'
      summary: 文章标签
      tags:
      - 文章管理
  /admin/category:
    delete:
      consumes:
      - multipart/form-data
      - application/x-www-form-urlencoded
      description: 删除分类 暂仅支持单个删除
      parameters:
      - description: 分类id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ApiResp'
        "302":
          description: Found
          schema:
            $ref: '#/definitions/util.ApiResp'
      summary: 分类删除
      tags:
      - 分类管理
    get:
      consumes:
      - multipart/form-data
      - application/x-www-form-urlencoded
      description: 分类列表，无分页，递归实现。
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ApiResp'
        "302":
          description: Found
          schema:
            $ref: '#/definitions/util.ApiResp'
      summary: 分类列表
      tags:
      - 分类管理
    post:
      consumes:
      - multipart/form-data
      - application/x-www-form-urlencoded
      description: 新增分类
      parameters:
      - description: 父级id
        in: formData
        name: pid
        required: true
        type: integer
      - description: 排序，数值越大越靠前
        in: formData
        name: order
        type: integer
      - description: 分类名称
        in: formData
        name: title
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ApiResp'
        "302":
          description: Found
          schema:
            $ref: '#/definitions/util.ApiResp'
      summary: 分类新增
      tags:
      - 分类管理
    put:
      consumes:
      - multipart/form-data
      - application/x-www-form-urlencoded
      description: 编辑分类
      parameters:
      - description: 分类id
        in: query
        name: id
        required: true
        type: integer
      - description: 父级id
        in: formData
        name: pid
        required: true
        type: integer
      - description: 排序，数值越大越靠前
        in: formData
        name: order
        type: integer
      - description: 分类名称
        in: formData
        name: title
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ApiResp'
        "302":
          description: Found
          schema:
            $ref: '#/definitions/util.ApiResp'
      summary: 分类更新
      tags:
      - 分类管理
  /admin/login:
    post:
      consumes:
      - multipart/form-data
      - application/x-www-form-urlencoded
      description: 统一登录接口，暂时接收账号密码登录和手机验证码登录
      parameters:
      - description: 登录类型1:用户名密码登录，2手机号验证码登录
        in: formData
        name: type
        required: true
        type: integer
      - description: 登录邮箱
        in: formData
        name: email
        type: string
      - description: 密码
        in: formData
        name: password
        type: string
      - description: 手机号
        in: formData
        name: phone
        type: string
      - description: 手机验证码
        in: formData
        name: captcha
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ApiResp'
        "302":
          description: Found
          schema:
            $ref: '#/definitions/util.ApiResp'
      summary: 登录
      tags:
      - 用户信息
  /admin/matieral/token:
    get:
      consumes:
      - multipart/form-data
      - application/x-www-form-urlencoded
      description: 上传图片获取七牛上传token-暂时仅支持上传，后期改为素材管理
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ApiResp'
        "302":
          description: Found
          schema:
            $ref: '#/definitions/util.ApiResp'
      summary: 获取上传token
      tags:
      - 素材管理
  /admin/tag:
    delete:
      consumes:
      - multipart/form-data
      - application/x-www-form-urlencoded
      description: 删除标签 暂仅支持单个删除
      parameters:
      - description: 标签id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ApiResp'
        "302":
          description: Found
          schema:
            $ref: '#/definitions/util.ApiResp'
      summary: 标签删除
      tags:
      - 标签管理
    get:
      consumes:
      - multipart/form-data
      - application/x-www-form-urlencoded
      description: 标签列表。
      parameters:
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页显示条数
        in: query
        name: limit
        type: integer
      - description: 名称筛选
        in: query
        name: title
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ListData'
        "302":
          description: Found
          schema:
            $ref: '#/definitions/util.ApiResp'
      summary: 标签列表
      tags:
      - 标签管理
    post:
      consumes:
      - multipart/form-data
      - application/x-www-form-urlencoded
      description: 新增标签
      parameters:
      - description: 排序，数值越大越靠前
        in: formData
        name: order
        type: integer
      - description: 标签名称
        in: formData
        name: title
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ApiResp'
        "302":
          description: Found
          schema:
            $ref: '#/definitions/util.ApiResp'
      summary: 标签新增
      tags:
      - 标签管理
    put:
      consumes:
      - multipart/form-data
      - application/x-www-form-urlencoded
      description: 编辑分类
      parameters:
      - description: 分类id
        in: query
        name: id
        required: true
        type: integer
      - description: 父级id
        in: formData
        name: pid
        required: true
        type: integer
      - description: 排序，数值越大越靠前
        in: formData
        name: order
        type: integer
      - description: 分类名称
        in: formData
        name: title
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ApiResp'
        "302":
          description: Found
          schema:
            $ref: '#/definitions/util.ApiResp'
      summary: 分类更新
      tags:
      - 标签管理
  /admin/user:
    delete:
      consumes:
      - multipart/form-data
      - application/x-www-form-urlencoded
      description: 删除管理员-暂只支持单个删除
      parameters:
      - description: 用户id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ApiResp'
        "302":
          description: Found
          schema:
            $ref: '#/definitions/util.ApiResp'
      summary: 管理员删除
      tags:
      - 用户信息
    get:
      consumes:
      - multipart/form-data
      - application/x-www-form-urlencoded
      description: 管理员列表
      parameters:
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页显示条数
        in: query
        name: limit
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ApiResp'
        "302":
          description: Found
          schema:
            $ref: '#/definitions/util.ApiResp'
      summary: 管理员列表
      tags:
      - 用户信息
    post:
      consumes:
      - multipart/form-data
      - application/x-www-form-urlencoded
      description: 新增管理员
      parameters:
      - description: 用户昵称
        in: formData
        name: nickname
        type: string
      - description: 用户真实姓名-用于登录使用
        in: formData
        name: realname
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      - description: 手机号-可用于登录
        in: formData
        name: phone
        required: true
        type: string
      - description: 邮箱
        in: formData
        name: email
        required: true
        type: string
      - description: 用户头像
        in: formData
        name: avatar
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ApiResp'
        "302":
          description: Found
          schema:
            $ref: '#/definitions/util.ApiResp'
      summary: 管理员新增
      tags:
      - 用户信息
    put:
      consumes:
      - multipart/form-data
      - application/x-www-form-urlencoded
      description: 编辑管理员
      parameters:
      - description: 用户id
        in: query
        name: id
        required: true
        type: integer
      - description: 用户昵称
        in: formData
        name: nickname
        type: string
      - description: 用户真实姓名-用于登录使用
        in: formData
        name: realname
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      - description: 手机号-可用于登录
        in: formData
        name: phone
        required: true
        type: string
      - description: 邮箱
        in: formData
        name: email
        required: true
        type: string
      - description: 用户头像
        in: formData
        name: avatar
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ApiResp'
        "302":
          description: Found
          schema:
            $ref: '#/definitions/util.ApiResp'
      summary: 管理员更新
      tags:
      - 用户信息
  /admin/user/:id:
    get:
      consumes:
      - multipart/form-data
      - application/x-www-form-urlencoded
      description: 根据主键ID获取管理员详情
      parameters:
      - description: 用户id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ApiResp'
        "302":
          description: Found
          schema:
            $ref: '#/definitions/util.ApiResp'
      summary: 管理员详情
      tags:
      - 用户信息
  /captcha:
    get:
      consumes:
      - multipart/form-data
      - application/x-www-form-urlencoded
      description: 获取图形验证码图片
      parameters:
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ApiResp'
        "302":
          description: Found
          schema:
            $ref: '#/definitions/util.ApiResp'
      summary: 图形验证码
      tags:
      - 公共接口
  /sms:
    post:
      consumes:
      - multipart/form-data
      - application/x-www-form-urlencoded
      description: 发送短信接口
      parameters:
      - description: 手机号
        in: formData
        name: phone
        required: true
        type: string
      - description: 图形验证码的值
        in: formData
        name: captcha
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ApiResp'
        "302":
          description: Found
          schema:
            $ref: '#/definitions/util.ApiResp'
      summary: 短信接口
      tags:
      - 公共接口
swagger: "2.0"
